image: gradle:7.6-jdk17-alpine

stages:
  - build
  - test
  - jacocoTest

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew
build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew :test --tests "tourGuide.**Test"
  allow_failure: true
  artifacts:
      when: always
      paths:
        - build/jacocoHtml
        - build/reports
        - build/jacoco/test.exec
      expire_in: 2 weeks
      reports:
        junit: build/test-results/test/TEST-*.xml

jacocoTest:
  stage: jacocoTest
  image: gradle:7.6-jdk17-alpine
  script:
    - 'gradle test jacocoTestReport' # jacoco must be configured to create an xml report
    - build/jacoco/jacoco.xml
  artifacts:
    paths:
      - build/jacoco/jacoco.xml
