image: gradle:7.6-jdk17-alpine

stages:
  - build
  - test
  - jacocoTest
  - visualize

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: gradle --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - gradle check
    - cat build/reports/tests/test/**/TEST-*.xml
    - cat build/reports/tests/test/**/index.html
  artifacts:
    reports:
      junit:
      - build/reports/tests/test/**/TEST-*.xml
      - build/reports/tests/test/**/index.html


jacocoTest:
  stage: jacocoTest
  image: gradle:7.6-jdk17-alpine
  script:
    - 'gradle test jacocoTestReport' # jacoco must be configured to create an xml report
    - cat build/jacoco/jacoco.xml
    - cat build/jacocoHtml/index.xml
  artifacts:
    paths:
      - build/jacoco/jacoco.xml
      - build/jacocoHtml/index.xml

coverage-jacoco:
  stage: visualize
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
      # convert report from jacoco to cobertura, using relative project path
      - python /opt/cover2cover.py build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
  needs: ["jacocoTest"]
  artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: build/cobertura.xml

