image: gradle:7.6-jdk17-alpine

stages:
  - compile
  - test
  - build
  - test-coverage
cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

compile:
  stage: compile
  script: ./gradlew compileJava
  only:
    - develop

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

    expire_in: 2 weeks
  only:
    - develop

test:
  stage: test
  script: ./gradle check
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml

test-coverage:
  stage: test-coverage
  script:
    - 'gradle clean test jacocoTestReport'
  artifacts:
    paths:
      - build/jacocoHtml
      - build/reports

    expire_in: 2 weeks
  only:
    - develop



