image: openjdk:17-alpine
check_gradle_version:
  image: openjdk:17-alpine
  script:
    - gradle --version
stages:
  - build
  - test
  - coverage
cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew test

jacocoTestReport:
  stage: coverage
  script:
    - ./gradlew test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
  coverage: '/Total instruction coverage:.+(\d+\.\d+)/'