image: gradle:7.6-jdk17-alpine

stages:
  - build
  - coverage
  - test
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 weeks

jacoco_coverage:
  stage: coverage
  script:
    - 'gradle clean test jacocoTestReport'
  artifacts:
    paths:
      - build/jacocoHtml
    expire_in: 2 weeks

test:
  stage: test
  script:
    - ./gradlew :test --tests "tourGuide.**"
  artifacts:
    paths:
      - build/reports
      - build/jacoco
      - build/jacocoHtml
    expire_in: 2 weeks
    reports:
      junit: build/test-results/test/TEST-*.xml

