image: gradle:7.6-jdk17-alpine

stages:
  - build
  - test

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  script: ./gradlew check
    - ./gradlew test jacocoTestReport # jacoco must be configured to create an xml report
  artifacts:
    paths:
      - build/jacoco/jacoco.xml
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'


