image: gradle:7.6-jdk17-alpine

stages:
  - build
  - testCoverage

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 weeks

testCoverage:
  stage: testCoverage
  script:
    - ./gradlew :test --tests "tourGuide.**"
    - 'gradle clean test jacocoTestReport'
  artifacts:
    paths:
      - build/jacocoHtml
      - build/reports
    expire_in: 2 weeks
    reports:
      junit: build/test-results/test/TEST-*.xml


