image: gradle:7.6-jdk17
stages:
  - build
  - test
  - test_unit
cache:
  paths:
    - build
    - .gradle
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    #-./gradlew test
    - gradle test jacocoTestReport
  artifacts:
    paths:
      - build/jacoco/jacoco.xml
      - build/jacoco/test.exec
      - build/jacocoHtml/index.html
  coverage: '/ - Instruction Coverage: ([0-9.]+)%/'

test_unit:
  stage: test_unit
  script:
    - ./gradlew :test --tests "tourGuide.**"
  artifacts:
   paths:
     - build/report-tests/test/Test-*.xml


