image: gradle:7.6-jdk17-alpine

stages:
  - compile
  - test
  - build
  - test-coverage
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

compile:
  stage: compile
  script: ./gradlew compileJava
  only:
    - develop

test:
  stage: test
  script: ./gradlew check
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 weeks
  only:
    - develop

test-coverage:
  stage: test-coverage
  script:
    - ./gradlew clean test jacocoTestReport
  artifacts:
    paths:
      - build/jacocoHtml
      - build/reports

    expire_in: 2 weeks
  only:
    - develop



