image: gradle:7.6-jdk17-alpine

stages:
  - build
  - test-coverage
  - test

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 2 weeks

test-coverage:
  stage: test-coverage
  script:
    - 'gradle clean test jacocoTestReport'
  artifacts:
    paths:
      - build/jacocoHtml
    expire_in: 2 weeks

test:
    stage: test
    script:
      - ./gradlew :test --tests "tourGuide.**"
    artifacts:
      paths:
        - build/reports
      expire_in: 2 weeks



