image: gradle:7.6-jdk17

stages:
  - build
  - test

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew clean test jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/xml/
      - build/reports/jacoco/test/jacocoTestReport.xml
  coverage: '/Total.*([0-9]{1,3}\%)/'
