image: gradle:7.6-jdk17

stages:
  - build
  - test
  - visualize

cache:
  paths:
    - build
    - .gradle

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x gradlew

build:
  stage: build
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs/*.jar

test:
  stage: test
  script:
    - ./gradlew clean jacocoTestReport
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml
  coverage: '/Overall coverage: ((\d{1,3}\.\d{1,2})%)/'

visualize:
  stage: visualize
  image: gradle:7.6-jdk17
  script:
    - ./gradlew jacocoTestReport
    - java -jar "$(find . -name 'jacoco-cli*.jar' | sort -r | head -1)" report build/jacoco/test.exec --classfiles build/classes --html build/reports/jacoco/test --xml build/reports/jacoco/test/jacocoTestReport.xml
  needs: [ "test" ]
  artifacts:
    paths:
      - build/reports/jacoco/test/html/
      - build/reports/jacoco/test/jacocoTestReport.xml
